In [ ]:
print("Hello World!")

Hello World!


In [ ]:
if 'cow' in ['dog', 'cat', 'cow']:
    print("cow is present")
if 'bat' not in ['dog', 'cat', 'cow']:
    print("bat is not present")


cow is present
bat is not present


In [ ]:
I=100 # item number
SP=120 #selling price
BP=100 # buying price
profit=I*SP - I*BP
print("the profit is:", profit)
loss= I*BP - I*SP
print("the loss is:", loss)

the profit is: 2000
the loss is: -2000


In [ ]:
a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
c=int(input("Enter third number: "))

if a>b:
      if a>c:
        print(a," is big")
      else:
        print(c,"is big" )
else:
      if b>c:
        print(b," is big")
      else:
        print(c," is big")

Enter first number: 25
Enter second number: 36
Enter third number: 15
36  is big


In [ ]:
x = int(input("enter a price:"))
if x<100:
        print("the price is less than 100")
elif  x>100:
        print("the price is greater than 100")
else:
        print("the price is 100")


enter a price:24
the price is less than 100


In [ ]:
x=8
if x<10:
    print("x is less than 10")
if x>10:
    print("x is greater than 10")


x is less than 10


In [ ]:
Age= 22
graduate= True
driving_license= False
if Age>=22:
  print("you are an adult")
  if graduate:
         print("you should be working person")
if driving_license:
         print("you can drive")
else:
         print("you cannot drive")


you are an adult
you should be working person
you cannot drive


In [ ]:
var = 220
if var<200:
  print("not expensive")
elif var >200:
  print("expensive")
else:
    print("not affordable ")

expensive


In [ ]:
a= float(input("enter the value"))
if a >0:
  print("positive")
elif a<0:
  print("negative")
else:
  print("zero")

enter the value-25
negative


In [ ]:
x=int(input("enter the number"))
if x%2==0:
  print("even")
else:
  print("odd")

enter the number8
even


In [ ]:
num=int(input("enter the number"))
if num & 1:
  print("number entered is odd")
else:
  print("number entered is even")

enter the number9
number entered is odd


In [ ]:
students=[ ["carry","maths",98],
          ["hena","physics",93],
          ["rama","chemistry",56]
]
 # a. print just the names and scores of all students
for student in students :
        print(student[0], student[2])
 #b. add new student record ["dave","biology",88] at the end
students.append(["dave","biology",88])
print(students)

 #c. update hena's score to 89
for student in students:
    if student[0]== "hena":
        student[2]=89
print(students)

carry 98
hena 93
rama 56
[['carry', 'maths', 98], ['hena', 'physics', 93], ['rama', 'chemistry', 56], ['dave', 'biology', 88]]
[['carry', 'maths', 98], ['hena', 'physics', 89], ['rama', 'chemistry', 56], ['dave', 'biology', 88]]


In [ ]:
""" sum of two numbers """
def sum(a,b):
     return a+b
a= float(input("enter the first number"))
b= float(input("enter the second number"))
print("sum=",sum(a,b))

enter the first number2.3
enter the second number5.7
sum= 8.0


In [ ]:
def greet(name="guest"):
    print("hello",name)
greet("carry")



hello carry


In [ ]:
""" keyword-lenght arguments"""
def gh(**x):
   for i in x.items():
    print(i)
gh(g=54,h=36,l="Hi everyone")

('g', 54)
('h', 36)
('l', 'Hi everyone')


In [ ]:
""" global and local variable"""
def display():
    m=33
    print("local variable m=",m)

m=46
print("global variable m=",m)
display()

global variable m= 46
local variable m= 33


In [ ]:
""" function returning a value"""
def find_square(num):
     result = num*num
     return result
square = find_square(3)
print("Square:",square)

Square: 9


In [ ]:
"""function with two arguments"""
def add_numbers(num1,num2):
  sum = num1+num2
  print("sum=",sum)
add_numbers(10,20)

sum= 30


In [ ]:
""" power function with default parameter"""
def power(base, exponent=2):
  return base ** exponent
print(power(3))
print(power(3,3))

9
27


In [ ]:
import numpy as np
arr1 = np.array([7,8,10])
arr2 = np.array([10,6,3])
arr3 = arr1+arr2
print(arr3)

[17 14 13]


In [ ]:
import numpy as np
arr1 = np.array([10,11,12,0,1,5])
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.size)
print(arr1.itemsize)

[10 11 12  0  1  5]
(6,)
int64
1
6
8


In [ ]:
import numpy as np
arr1 = np.array([[10,11],[12,0],[1,5],[23,42]])
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.size)
print(arr1.itemsize)

[[10 11]
 [12  0]
 [ 1  5]
 [23 42]]
(4, 2)
int64
2
8
8


In [ ]:
# creating 3D array
import numpy as np
arr1 = np.array([[[10,11,0],[12,0,14]],[[1,5,6],[23,42,11]]])
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.size)


[[[10 11  0]
  [12  0 14]]

 [[ 1  5  6]
  [23 42 11]]]
(2, 2, 3)
int64
3
12


In [ ]:
# specify datatype
import numpy as np
arr1 = np.array([10,11,12,0,1,5])
print(arr1)
print(arr1.dtype)
print(arr1.itemsize)
arr2 = np.array([10,11,12,0,1,5], dtype=float)
print(arr2)
print(arr2.dtype)
print(arr2.itemsize)


[10 11 12  0  1  5]
int64
8
[10. 11. 12.  0.  1.  5.]
float64
8


In [ ]:
# creating arrays filled with zeros
import numpy as np
arr1 = np.zeros(3)
print(arr1)
arr2= np.zeros(3,dtype=int)
print(arr2)
arr3= np.zeros((2,3,4))
print(arr3)

[0. 0. 0.]
[0 0 0]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#identity matrix
import numpy as np
arr1= np.eye(3)
print(arr1)
# matrix with given value
arr2= np.full((3,4),5)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
 # numpy.arrage()
 import numpy as np
 arr1= np.arange(5)
 print(arr1)
 arr2= np.arange(5,10)
 print(arr2)
 arr3= np.arange(5,10,2)
 print(arr3)

[0 1 2 3 4]
[5 6 7 8 9]
[5 7 9]


In [ ]:
#numpy.linspace()
import numpy as np
arr1= np.linspace(0,10,5)
print(arr1)
arr2= np.linspace(0,15,4)
print(arr2)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  5. 10. 15.]


In [ ]:
#sorting array elemnts
import numpy as np
arr1= np.array([31,91,23,54,2,23,0])
arr2 = np.sort(arr1)
print(arr1)
print(arr2)


[31 91 23 54  2 23  0]
[ 0  2 23 23 31 54 91]


In [ ]:
#sqaure root
import numpy as np
arr1= np.array([1,4,9,16,25])
arr2= np.sqrt(arr1)
print(arr1)
print(arr2)
arr3= np.array([25,5,297,625])
arr4 = np.sqrt(arr3)
print(arr3)
print(arr4)


[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]
[ 25   5 297 625]
[ 5.          2.23606798 17.23368794 25.        ]


In [ ]:
# mean variance and standard devivation
import numpy as np
arr1= np.array([1,2,3,4,5])
print("mean=",np.mean(arr1))
print("variance=",np.var(arr1))
print("standard deviation=",np.std(arr1))
arr2= np.array([5,10,15,20,25])
print("mean=",np.mean(arr2))
print("variance=",np.var(arr2))
print("standard deviation=", np.std(arr2))

mean= 3.0
variance= 2.0
standard deviation= 1.4142135623730951
mean= 15.0
variance= 50.0
standard deviation= 7.0710678118654755


In [ ]:
# reshaping
import numpy as np
arr1= np.arange(12)
print(arr1)
arr2= arr1.reshape(2,6)
print(arr2)
arr3= arr1.reshape(3,4)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#flattening
import numpy as np
arr1= np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.flatten())
print(arr1.reshape(-1))
print((arr1.reshape(-1).shape))


[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
[1 2 3 4 5 6]
(6,)


In [ ]:
#indexing
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr1[0],arr1[1])
print(arr1[-1],arr1[-2])

1 2
6 5


In [ ]:
# slicing
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[0:8:2])
print(arr1[3:8:3])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)
print(arr2[0:2, 1:3])

[1 3 5 7]
[4 7]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
# bradcasting
import numpy as np
arr1= np.array([[1,2,3],[4,5,6]])
arr2 = arr1*10
print("arr1=",arr1)
print("arr1*10=",arr2)
arr3= np.array([1,2,3])
arr4= arr1+arr3
print("arr1+arr3=",arr4)


arr1= [[1 2 3]
 [4 5 6]]
arr1*10= [[10 20 30]
 [40 50 60]]
arr1+arr3= [[2 4 6]
 [5 7 9]]


In [ ]:
# linar algebra
import numpy as np
Ma= np.array([[1,2],[4,5]])
Mb= np.array([[2,3],[5,6]])
mu1= np.dot(Ma,Mb)
print("Ma*Mb=",mu1)
M1= np.array([[1,2,3],[4,5,6],[11,34,10]])
Ma_det= np.linalg.det(M1)
print("Ma_det=",Ma_det)

Ma*Mb= [[12 15]
 [33 42]]
Ma_det= 141.00000000000003
